version: '3.8'
services:
  sevice:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - SESSION_SECRET=${SESSION_SECRET}
        - JWT_SECRET=${JWT_SECRET}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - my-network
  slice-postgres:
    image: postgres:12.0
    container_name: slice-ai-postgres
    env_file:
      - .env
    ports:
      - '5438:5432'
    networks:
      - my-network
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

networks:
  my-network:
    driver: bridge
